spring.application.name=osrsstats
spring.datasource.url=jdbc:postgresql://localhost:5432/osrsstats
spring.datasource.username=osrs
spring.datasource.password=osrs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=10m